version: '3.8'

services:
  pgdb:
    image: postgres:15
    container_name: expenses_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: expenses
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: ./be
      dockerfile: Dockerfile
    container_name: backend
    env_file:
      - ./be/.env
    ports:
      - "3000:3000"
    depends_on:
      - pgdb

volumes:
  pgdata:
