version: '3.8'

services:
  pgdb:
    image: postgres:15
    container_name: expenses_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: expenses
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: ./be
      dockerfile: Dockerfile
    container_name: backend
    env_file:
      - ./be/.env
    ports:
      - "3000:3000"
    depends_on:
      - pgdb

  frontend:
    build:
      context: ./fe
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3001:3000" 
    volumes:
      - ./fe:/app
      - /app/node_modules 
    command: ["npm", "start"]
    environment:
    - NODE_ENV=production
    - REACT_APP_API_URL=https://sheet-api.insky.fun
    depends_on:
      - backend

  nginx:
    image: nginx:alpine
    container_name: gateway
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./conf:/etc/nginx/conf
    restart: always

volumes:
  pgdata:
